version: 0.2
env:
  secrets-manager:
    MONGODB_URL: "PRAJWAL_MONGO_SECRET:mongodb_url"
    
phases: 
  pre-build:
    commands: 
      - echo Build started on `date`
      - echo "MONGODB_URL_PRAJWAL=$MONGODB_URL" > .env
      
  build:
    commands: 
      - npm install
      - npm install --save dotenv
      
  post-build:
    commands: 
      - echo Build completed on `date`
      
artifacts:
  files:
    - '**/*'
